# Generated by Django 5.1.7 on 2025-04-18 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_favorite_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Singapore phone number (e.g., 91234567 or +6591234567).', regex='^(\\+65)?[689]\\d{7}$')]),
        ),
    ]
